export const API_PATH = {
  CYCLE: '/cycles',
  CYCLES_ID: '/cycles/:cycleId',
};

export const CLIENT_PATH = {
  HOME: '/home',
  LOGIN: '/login',
  SIGN_UP: '/sign_up',
  CERT: '/cert',
  CHALLENGE_SEARCH: '/challenge/search',
  CHALLENGE_EVENT: '/challenge/event',
  FEED: '/feed',
  FEED_DETAIL: '/feed/detail',
  FEED_DETAIL_ID: '/feed/detail/:cycleDetailId',
  PROFILE: '/profile',
  PROFILE_EDIT: '/profile/edit',
  PROFILE_CHALLENGE_DETAIL: '/profile/challenges/detail',
  PROFILE_CHALLENGE_DETAIL_ID: '/profile/challenges/detail/:challengeId',
  CYCLE_DETAIL: '/cycle/detail',
  CYCLE_DETAIL_ID: '/cycle/detail/:cycleId',
  CYCLE_DETAIL_SHARE: '/cycle/detail/share',
  CYCLE_DETAIL_SHARE_ID: '/cycle/detail/share/:cycleId',
  CHALLENGE_CREATE: '/challenge/create',
  CHALLENGE_DETAIL: '/challenge/detail',
  CHALLENGE_DETAIL_ID: '/challenge/detail/:challengeId',
  RANK: '/ranks',
  VOC: '/voc',
  NOT_FOUND: '/not_found',
  WILD_CARD: '*',
};
