export { NotFoundPage } from 'pages/NotFoundPage';
export { Home } from 'pages/Home';
export { SignUpPage } from 'pages/SignUpPage';
export { LoginPage } from 'pages/LoginPage';
export { SearchPage } from 'pages/SearchPage';
export { ProfilePage } from 'pages/ProfilePage';
export { ChallengeDetailPage } from 'pages/ChallengeDetailPage';
export { CertPage } from 'pages/CertPage';
export { CertUnAuthPage } from 'pages/CertUnAuthPage';
