name: Frontend CI

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - frontend/**
      - .github/** # Github Actions 작업을 위한 포함

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.10.0'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install node packages
        run: yarn

      - name: Run tests
        run: |
          npx jest --silent --coverage --coverageReporters json-summary

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./src/coverage/coverage-summary.json
          title: Frontend Test
          summary-title: Jest Coverage
          badge-title: Coverage
          create-new-comment: true

      - name: Component test
        run: yarn run test

      - name: TypeScript test
        run: yarn run typecheck
